// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_clean_arch/test/presentation/feature/movie/movie_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_clean_arch/domain/data_wrapper/api_result.dart' as _i2;
import 'package:flutter_clean_arch/domain/model/movie_item.dart' as _i5;
import 'package:flutter_clean_arch/domain/usecase/get_movie_list_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetMovieListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieListUseCase extends _i1.Mock
    implements _i3.GetMovieListUseCase {
  MockGetMovieListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<List<_i5.MovieItem>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i4.Future<_i2.ApiResult<List<_i5.MovieItem>>>.value(
            _FakeApiResult_0<List<_i5.MovieItem>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<List<_i5.MovieItem>>>);
}
